### ISSUE TITLE
meta suivi

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/savoirfR#1]
- [x] création du squelette du package

## Module 1
- [x] intégration des jeux de donnée
- [x] création des rmd correspondant aux énoncés
- [x] création des rmd correspondant aux corrigés 

## Module 2
- [x] intégration des jeux de donnée
- [x] création des rmd correspondant aux énoncés
- [x] création des rmd correspondant aux corrigés 

## Module 3 
- [ ] intégration des jeux de donnée
- [ ] création des rmd correspondant aux énoncés
- [ ] création des rmd correspondant aux corrigés 

## Module 4 
- [ ] intégration des jeux de donnée
- [ ] création des rmd correspondant aux énoncés
- [ ] création des rmd correspondant aux corrigés 

## Module 5 
- [x] intégration des jeux de donnée
- [x] création des rmd correspondant aux énoncés
- [x] création des rmd correspondant aux corrigés 

## Module 6 
- [ ] intégration des jeux de donnée
- [ ] création des rmd correspondant aux énoncés
- [ ] création des rmd correspondant aux corrigés 

## Module 7 
- [ ] intégration des jeux de donnée
- [ ] création des rmd correspondant aux énoncés
- [ ] création des rmd correspondant aux corrigés

**Comment by jengelaere** [comment]
Le but c'est d'avoir des jeux de données communs entre les modules ? On ne reprend pas les exo préexistants ?

**Comment by MaelTheuliere** [comment]
@jengelaere  Oui c'est ça, mais le jeu de donnée peut être assez large, et on peut partir des exos existant ou en rajouter.

**Comment by MaelTheuliere** [comment]
Suggestion reçu sur tchap : utiliser les données covid : https://www.data.gouv.fr/fr/datasets/donnees-relatives-a-lepidemie-du-covid-19/

**Comment by MaelTheuliere** [comment]
@jengelaere @TerseurBr @MZellou  vous avez le temps d'avancer dessus ou c'est trop compliqué en ce moment ? Je pense que cela serait utile par rapport à la demande de Sylvie sur la capacité à faire de la formation à distance.

**Comment by MZellou** [comment]
Je devrais pouvoir avancer dessus d'ici 2 petites semaines ! Je commence à voir le bout de la collecte RPLS

**Comment by jengelaere** [comment]
Je suis en train de travailler sur le M2, ce devrait être fini sous une semaine

**Comment by TerseurBr** [comment]
Bonsoir Mael

meme réponse, je pense semaine prochaine, pas pu bénéficier fin avril de la fenetre de calme espérée, mais je vais m'y remettre

**Comment by jengelaere** [comment]
Bonjour à tous, c'est bon pour le M2 ! J'ai fait ma MR et ai demandé à Maël et à Murielle d'y regarder, comme ils ont fini leur module !

**Comment by MaelTheuliere** [comment]
Désolé @MurielleL , tu vas croire que je t'en veux ! je n'avais vu que moi en relviewer...

**Comment by MaelTheuliere** [comment]
Attention, j'ai tout basculé pour remettre le repo en cohérence avec le nom du package; Merci de recloner le projet
